# 服务器相关
server:
  port: 8081

spring:
  application:
    name: mini-blog-client

  thymeleaf:  #thymeleaf信息配置
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false

  resources:  #静态资源设置
    static-locations: classpath:/static/**

eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  eureka:
    enabled: true
